### ISSUE TITLE
Java examples for graph sdk….

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/graph-sdk#116]
As we roll out graphsdk to external providers we want some Java examples of using the SDK in detail in a list of scenarios:

- [x] Add a new Graph Key
- [x] Public Follow and Unfollow
- [x] Private Follow and Unfollow
- [x] Make / Break Private Connection (double opt-in)
- [x] Rotate Key
- [x] Get List of Graph Keys
- [ ] Other?

**Comment by aramikm** [comment]
examples are provided in https://github.com/AmplicaLabs/saas-frequency-client/pull/56 PR
