### ISSUE TITLE
[GraphSDK] create a new API endpoint to be able to generate X25519 keys

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/graph-sdk#127]
# Why
When doing integrations with Saas client it became obvious that they only have access to Sr25519 keys and can not generate any X25519 keys which we use for the graph. All alternative JVM libraries that generate x25519 are heavy weight and not that great so it makes sense to provide this functionality as an api in GraphSdk to allow generating new x25519 keys without adding a new library.

# What
- [x] Add a new api endpoint `generate_keypair(key_type: GraphKeyType)` to graph sdk which does not require state. Please follow the same pattern as **deserialize_dsnp_keys** endpoint which does not have `&self` as a param.
- [x] Add JNI, FFI, Node bridges
- [x] Add integration test in Rust/Java/FFI/Node

# Notes
- It seems like that wallet currently does not support x25519 and we have to communicate with wallet teams to add the support for those type of keys
- Ensure that keys being generated are unique and use randomness provided by OS or device. One option to just use `StackKeyPair::gen()` from **dryoc** library which is using the same implementation as lib-sodium

**Comment by saraswatpuneet** [comment]
Question:
Do we need api for ffi? c/c++ can use libsodium

**Comment by aramikm** [comment]
I think we should have it so that all the apis are uniform across all languages
