### ISSUE TITLE
[graph-sdk] Add docs/examples for Rust & Java

### ISSUE THREAD

**Issue by JoeCap08055** [LibertyDSNP/graph-sdk#150]
Providers & other developers will require example code to show how to interact with GraphSDK.

**Comment by aramikm** [comment]
We do have some of it in docs and kotlin examples. Would you mind add more details?

**Comment by JoeCap08055** [comment]
@aramikm , @wilwade thought it best to embed the examples in this repo instead of linking to another repo; I mostly copied & edited the kotlin example you did, plus added a couple new flow diagrams.
