### ISSUE TITLE
[bug] [graph-sdk] Adding redundant connection throws an error

### ISSUE THREAD

**Issue by JoeCap08055** [LibertyDSNP/graph-sdk#153]
Using the npm bridge, when trying to add a connection that already exists to a graph using `applyActions`, an error is thrown.

Actual behavior: an error is thrown (npm bridge)

Expected behavior: operation is a no-op/silently fails

**Comment by saraswatpuneet** [comment]
hmm not sure if it is a bug in the state itself, bridge just sends the actions to core api 

`pub fn apply_actions(mut cx: FunctionContext) -> JsResult<JsBoolean> {
	let graph_state_id: Handle<'_, JsNumber> = cx.argument::<JsNumber>(0)?;
	let graph_state_id = graph_state_id.value(&mut cx) as usize;
	let actions: Handle<'_, JsArray> = cx.argument::<JsArray>(1)?;
	let rust_actions: Vec<Action> = actions_from_js(&mut cx, actions)?;

	let mut states = GRAPH_STATES.lock().unwrap();
	let graph_state = states.get_mut(&graph_state_id);
	if graph_state.is_none() {
		return cx.throw_error("Graph state not found")
	}
	let graph_state = graph_state.unwrap();
	let mut graph_state = graph_state.lock().unwrap();

	let apply_result = graph_state.apply_actions(&rust_actions);
	match apply_result {
		Ok(_) => Ok(cx.boolean(true)),
		Err(e) => cx.throw_error(e.to_string()),
	}
}`

**Comment by saraswatpuneet** [comment]
disregard that i found the bug

**Comment by saraswatpuneet** [comment]
So we want this to fail silently?

**Comment by JoeCap08055** [comment]
> So we want this to fail silently?

I think so; it seems like a much better user experience for client code. The SDK is smart enough to figure it all out.

**Comment by saraswatpuneet** [comment]
So i all of our bridges we throw error, so ideally we should not throw error from `core` `api` itself if there is duplicate connection?

**Comment by JoeCap08055** [comment]
> > So i all of our bridges we throw error, so ideally we should not throw error from core api itself if there is duplicate connection?
> 
> I think there are arguments supporting both of those decisions. From client perspective they don't have to take care of connection duplication error but on the other hand we are kinda hiding that just added connection already existed which might be indicator of a bigger inconsistency problem between graph data in provider side and graph data stored on chain.

Perhaps a flag `allowExistingConnections: boolean` as an input parameter to `apply_actions`?

**Comment by aramikm** [comment]
That is an option but we would need to modify all the docs and examples everywhere. An other option is to set it up part of the configuration (behavioral config) and when we are initiating the sdk we can pass that as a param but that would need more effort. I don't have strong opinions which way we choose.
