### ISSUE TITLE
[graph-sdk] SPIKE: Publish multi-architecture prebuilt binaries for Node.js

### ISSUE THREAD

**Issue by JoeCap08055** [LibertyDSNP/graph-sdk#154]
Currently, the published npm package `@dsnp/graph-sdk` only supports the `linux/amd64` or `linux/x86_64` architecture, because that's the architecture of the GitHub CI runner that runs the package publish pipeline. In order to properly support Node.js developers, we need to support multiple architectures. This could be achieved in several ways:

* Using something akin to [node-gyp](https://github.com/nodejs/node-gyp), which installs native modules from C/C++ source with installation-time compilation. Could this be adapted (or is there another tool) for Rust?
* Using [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) to manage publishing pre-built binaries for some common architectures.
  * This would likely necessitate some modification of the `cargo` manifests to be able to cross-compile multiple different target architectures in a single build environment.
* Enable the `wasm` target for `graph-sdk` so that only a wasm environment is required. This may be necessary anyway to support browser & mobile...
* Other?

Desired output:
* Analysis & decision of an appropriate solution, with a working sample

## Notes:
See [this issue](https://github.com/neon-bindings/neon/issues/117) (especially the discussion).

**Comment by saraswatpuneet** [comment]
I would say `wasm` would be ideal but due to unknown amount of work that it might need, `node-gyp` is used everywhere else e.g. `libsignal`

**Comment by aramikm** [comment]
This is done in #180
