### ISSUE TITLE
[graph-sdk] SPIKE: publish JAR with multi-architecture native component

### ISSUE THREAD

**Issue by JoeCap08055** [LibertyDSNP/graph-sdk#155]
Currently, the published JAR file only supports the `linux/amd64` or `linux/x86_64` architecture, because that's the architecture of the GitHub CI runner that runs the package publish pipeline. In order to properly support JVM-based language developers, we need to support multiple architectures.

* Research existing projects that deploy JARs with native components. How do they handle multi-architecture?
* This would likely necessitate some modification of the `cargo` manifests to be able to cross-compile multiple different target architectures in a single build environment.
* Research WASM support in Java; is it possible to enable the `wasm` target for `graph-sdk` so that only a wasm binary is required. This may be necessary anyway to support browser & mobile...
* Other?

Desired output:
* Analysis & decision of an appropriate solution, with a working sample

**Comment by aramikm** [comment]
This is done in #180
