### ISSUE TITLE
[bug] Unable to import DSNP public keys without schema ID, and import with empty pages still clears graph state

### ISSUE THREAD

**Issue by JoeCap08055** [LibertyDSNP/graph-sdk#168]
1. As a client of the GraphSDK API, I should be able to import a user's public DSNP graph keys ONLY, without importing the entire graph. Currently the import function assumes that `schema_id` is present in the import bundle

2. If I import only public DSNP  keys with a zero-length vector of pages, the existing graph state for the user is still cleared. I should be able to import only public keys; If no pages are present in the import bundle, the graph state should be untouched. _(Note: if it is desired to be able to clear a user graph, it could be removed and re-added to the graph state, or an additional `clear_user_graph` method could be created)_

**Comment by saraswatpuneet** [comment]
Yes if we can make schemaId optional for keys only will be useful

**Comment by aramikm** [comment]
For the first one we can just modify `validate` implemented for `ImportBundle` to only enforce schema existence if pages are not empty.

For the second one maybe just get rid on `graph.clear()` on import but we would need to make sure if we are re importing an existing page then it should overwrite it
