### ISSUE TITLE
[GraphSDK] comprehensive logging

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/graph-sdk#43]
We would like to add comprehensive logging:

AC:

- support levels of logging [debug, info, warn, error]
- add logs to important places

open questions:

- research best practices on exposing logs in an SDK in rust

**Comment by JoeCap08055** [comment]
Should most likely use the Rust `log` crate as the standard API; it allows you to plug in a custom logger implementation, so it would tie in with any FFI or JNI logging bridges we develop.

For #64 I'm planning on implementing a custom logger that conforms to the `log` crate API.
