### ISSUE TITLE
[GraphSDK] Implement Graph and Page Structs

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/graph-sdk#5]
## Acceptance Criterea
- implement `Graph` and `Page` structs
- Each struct should be self contained and expose methods to interact with them
- Suggested methods for `Page`
   - **new**: initializing a page with page number and connections
   - **contains**: checks if a connection exists in the page
   - **is_empty**: checks if a page is empty
   - **add**: adds a connection to the page
   - **remove**: removes a connection from the page
- Suggested methods for `Graph`
   - **new**: initializing a graph with privacy level and connection types
   - **create_page**: create a page with page number and existing connections
   - **get_page**: exposes a page with page number
   - **get_connections**: returns all connections with the pages that they are in
   - **find**: returns page number of a connection if it exists in the graph and None if not
   - **add**: adds a connection to a certain page
   - **remove**: removes a connection from a certain page
- write tests

## additional info
Data model and details are located at https://github.com/LibertyDSNP/frequency/blob/main/designdocs/graph_sdk.md

**Comment by JoeCap08055** [comment]
@aramikm -- qq regarding this for `Graph` operations:

- add: adds a connection _to a certain page_
- remove: removes a connection _from a certain page_

Should we remove "to a certain page" here for Graph? I'm thinking that for "add", the page to which we add a connection would be determined by internal optimization logic (and likely not until the time of final evaluation for update). For "remove", we should remove the connection from any page(s) we find it in. If a client wants to operate on a specific page, they can "get" the page and operate on it directly. Graph operations should be more holistic.

Agree?
